const cidadesComBairros: Record<string, string[]> = {
  Alta_Floresta: [],
  Araputanga: [],
  Barra_do_Bugres: [],
  Barra_do_Garças: [],
  Cáceres: [],
  Campo_Novo_do_Parecis: [],
  Canarana: [],
  Chapada_dos_Guimarães: [],
  Colíder: [],
  Cuiabá: [],
  Guarantã_do_Norte: [],
  Jaciara: [],
  Juara: [],
  Juína: [],
  Lucas_do_Rio_Verde: [],
  Matupá: [],
  Mirassol_d_Oeste: [],
  Nobres: [],
  Nova_Mutum: [],
  Nossa_Senhora_do_Livramento: [],
  Peixoto_de_Azevedo: [],
  Poconé: [],
  Pontes_e_Lacerda: [],
  Primavera_do_Leste: [],
  Rondonópolis: [],
  Rosário_Oeste: [],
  Sapezal: [],
  Sinop: [],
  Sorriso: [],
  Santo_Antonio_do_Leverger: [],
  Tangará_da_Serra: [],
  Várzea_Grande: [],
  Vila_Rica: []
};

export default cidadesComBairros;