export const ITENS_POR_SETOR: Record<string, { chave: string; label: string }[]> = {
  Residencial: [
    { chave: "quartos", label: "Quartos" },
    { chave: "suites", label: "Suítes" },
    { chave: "banheiros", label: "Banheiros" },
    { chave: "garagens", label: "Vagas de Garagem" },
    { chave: "salas", label: "Salas de Estar" },
    { chave: "cozinhas", label: "Cozinhas" },
    { chave: "closets", label: "Closets" },
    { chave: "lavanderias", label: "Lavanderias" },
    { chave: "varandas", label: "Varandas" },
    { chave: "escritorios", label: "Escritórios" },
    { chave: "despensas", label: "Despensas" },
    { chave: "piscinas", label: "Piscina" },
    { chave: "churrasqueiras", label: "Churrasqueira" },
    { chave: "jardins", label: "Jardim" },
    { chave: "playgrounds", label: "Playground" },
    { chave: "academias", label: "Academia" },
    { chave: "arCondicionado", label: "Ar Condicionado" },
    { chave: "moveisPlanejados", label: "Móveis Planejados" },
    { chave: "areaGourmet", label: "Área Gourmet" },
    { chave: "salaJantar", label: "Sala de Jantar" },
    { chave: "salaTV", label: "Sala de TV" },
    { chave: "sacada", label: "Sacada" },
    { chave: "deposito", label: "Depósito" },
    { chave: "quartoEmpregada", label: "Quarto de Empregada" },
    { chave: "banheiroEmpregada", label: "Banheiro de Empregada" },
  ],
  Comercial: [
    { chave: "salas", label: "Salas" },
    { chave: "banheiros", label: "Banheiros" },
    { chave: "garagens", label: "Vagas de Garagem" },
    { chave: "recepcao", label: "Recepção" },
    { chave: "deposito", label: "Depósito" },
    { chave: "elevadores", label: "Elevadores" },
    { chave: "copa", label: "Copa" },
    { chave: "arCondicionado", label: "Ar Condicionado" },
    { chave: "portarias", label: "Portaria 24h" },
    { chave: "auditorio", label: "Auditório" },
    { chave: "vitrine", label: "Vitrine" },
    { chave: "mezanino", label: "Mezanino" },
    { chave: "docas", label: "Docas" },
    { chave: "almoxarifado", label: "Almoxarifado" },
    { chave: "estacionamentoVisitantes", label: "Estacionamento Visitantes" },
  ],
  Rural: [
    { chave: "hectares", label: "Hectares" },
    { chave: "casasFuncionarios", label: "Casas de Funcionários" },
    { chave: "galpoes", label: "Galpões" },
    { chave: "casaSede", label: "Casa Sede" },
    { chave: "curral", label: "Curral" },
    { chave: "energia", label: "Energia" },
    { chave: "agua", label: "Água" },
    { chave: "represa", label: "Represa" },
    { chave: "pocoArtesiano", label: "Poço Artesiano" },
    { chave: "mangueiro", label: "Mangueiro" },
    { chave: "pastagem", label: "Pastagem" },
    { chave: "arvoresFrutiferas", label: "Árvores Frutíferas" },
    { chave: "cercas", label: "Cercas" },
    { chave: "trator", label: "Trator" },
    { chave: "silo", label: "Silo" },
    { chave: "canavial", label: "Canavial" },
    { chave: "estabulo", label: "Estábulo" },
    { chave: "chiqueiro", label: "Chiqueiro" },
    { chave: "horta", label: "Horta" },
    { chave: "tanquePeixes", label: "Tanque de Peixes" },
  ],
};

export const ITENS_QUANTITATIVOS = [
  "quartos", "suites", "banheiros", "garagens", "cozinhas", "closets", "hectares", "casasFuncionarios", "galpoes", "salas"
];