export const ITENS_POR_SETOR: Record<string, { chave: string; nome: string; icone: string }[]> = {
  Residencial: [
    { chave: "quartos", nome: "Quartos", icone: "🛏️" },
    { chave: "suites", nome: "Suítes", icone: "🚿" },
    { chave: "banheiros", nome: "Banheiros", icone: "🚽" },
    { chave: "garagens", nome: "Vagas de Garagem", icone: "🚗" },
    { chave: "salas", nome: "Salas de Estar", icone: "🛋️" },
    { chave: "cozinhas", nome: "Cozinhas", icone: "🍳" },
    { chave: "closets", nome: "Closets", icone: "👗" },
    { chave: "lavanderias", nome: "Lavanderias", icone: "🧺" },
    { chave: "varandas", nome: "Varandas", icone: "🪑" },
    { chave: "escritorios", nome: "Escritórios", icone: "💻" },
    { chave: "despensas", nome: "Despensas", icone: "📦" },
    { chave: "piscinas", nome: "Piscina", icone: "🏊" },
    { chave: "churrasqueiras", nome: "Churrasqueira", icone: "🔥" },
    { chave: "jardins", nome: "Jardim", icone: "🌿" },
    { chave: "playgrounds", nome: "Playground", icone: "🛝" },
    { chave: "academias", nome: "Academia", icone: "💪" },
    { chave: "arCondicionado", nome: "Ar Condicionado", icone: "❄️" },
    { chave: "moveisPlanejados", nome: "Móveis Planejados", icone: "🪑" },
    { chave: "areaGourmet", nome: "Área Gourmet", icone: "🍽️" },
    { chave: "salaJantar", nome: "Sala de Jantar", icone: "🍽️" },
    { chave: "salaTV", nome: "Sala de TV", icone: "📺" },
    { chave: "sacada", nome: "Sacada", icone: "🏡" },
    { chave: "deposito", nome: "Depósito", icone: "📦" },
    { chave: "quartoEmpregada", nome: "Quarto de Empregada", icone: "🛏️" },
    { chave: "banheiroEmpregada", nome: "Banheiro de Empregada", icone: "🚿" },
  ],
  Comercial: [
    { chave: "salas", nome: "Salas", icone: "🏢" },
    { chave: "banheiros", nome: "Banheiros", icone: "🚽" },
    { chave: "garagens", nome: "Vagas de Garagem", icone: "🚗" },
    { chave: "recepcao", nome: "Recepção", icone: "🎯" },
    { chave: "deposito", nome: "Depósito", icone: "📦" },
    { chave: "elevadores", nome: "Elevadores", icone: "🛗" },
    { chave: "copa", nome: "Copa", icone: "☕" },
    { chave: "arCondicionado", nome: "Ar Condicionado", icone: "❄️" },
    { chave: "portarias", nome: "Portaria 24h", icone: "🛡️" },
    { chave: "auditorio", nome: "Auditório", icone: "🎤" },
    { chave: "vitrine", nome: "Vitrine", icone: "🪟" },
    { chave: "mezanino", nome: "Mezanino", icone: "🏗️" },
    { chave: "docas", nome: "Docas", icone: "🚚" },
    { chave: "almoxarifado", nome: "Almoxarifado", icone: "📦" },
    { chave: "estacionamentoVisitantes", nome: "Estacionamento Visitantes", icone: "🅿️" },
  ],
  Rural: [
    { chave: "hectares", nome: "Hectares", icone: "🌾" },
    { chave: "casasFuncionarios", nome: "Casas de Funcionários", icone: "🏠" },
    { chave: "galpoes", nome: "Galpões", icone: "🏗️" },
    { chave: "casaSede", nome: "Casa Sede", icone: "🏡" },
    { chave: "curral", nome: "Curral", icone: "🐄" },
    { chave: "energia", nome: "Energia", icone: "⚡" },
    { chave: "agua", nome: "Água", icone: "💧" },
    { chave: "represa", nome: "Represa", icone: "🌊" },
    { chave: "pocoArtesiano", nome: "Poço Artesiano", icone: "💧" },
    { chave: "mangueiro", nome: "Mangueiro", icone: "🐎" },
    { chave: "pastagem", nome: "Pastagem", icone: "🌱" },
    { chave: "arvoresFrutiferas", nome: "Árvores Frutíferas", icone: "🍎" },
    { chave: "cercas", nome: "Cercas", icone: "🚧" },
    { chave: "trator", nome: "Trator", icone: "🚜" },
    { chave: "silo", nome: "Silo", icone: "🌾" },
    { chave: "canavial", nome: "Canavial", icone: "🎋" },
    { chave: "estabulo", nome: "Estábulo", icone: "🐄" },
    { chave: "chiqueiro", nome: "Chiqueiro", icone: "🐷" },
    { chave: "horta", nome: "Horta", icone: "🥬" },
    { chave: "tanquePeixes", nome: "Tanque de Peixes", icone: "🐟" },
  ],
};

export const ITENS_QUANTITATIVOS = [
  "quartos", "suites", "banheiros", "garagens", "cozinhas", "closets", "hectares", "casasFuncionarios", "galpoes", "salas"
];